[package]
name = "try-rs"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "try"
path = "src/main.rs"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
crossterm = "0.27"
dirs = "5.0"
chrono = { version = "0.4", features = ["serde"] }
anyhow = "1.0"
is-terminal = "0.4"
